from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
from enum import Enum

class DecisionStatus(str, Enum):
    REJECTED = "REJECTED"
    ADVISORY = "ADVISORY"
    ELIGIBLE_FOR_REVIEW = "ELIGIBLE_FOR_REVIEW"
    PENDING = "PENDING"

class PrestigeData(BaseModel):
    """Data from the Prestige commercial layer (search, journeys)."""
    journey_id: str
    origin: str
    destination: str
    searches_last_24h: int
    conversion_rate: float
    competitor_prices: Dict[str, float]

class BookingData(BaseModel):
    """Booking and occupancy data."""
    route_id: str
    total_capacity: int = Field(gt=0)
    booked_seats: int
    avg_lead_time_days: float
    cancellation_rate: float
    last_booking_timestamp: datetime

class FinanceData(BaseModel):
    """Financial and tax data (MIRA compliant)."""
    transaction_id: str
    base_amount: float
    service_charge: float = 0.10  # 10%
    tgst: float = 0.17           # 17%
    total_amount: float
    currency: str = "USD"

class AiDecision(BaseModel):
    """Actionable instruction generated by the AI Layer with strict policy fields."""
    module: str  # routing_optimizer, demand_predictor, revenue_optimizer
    action: str
    reasoning: str
    parameters: Dict[str, Any]
    confidence_score: float

    # New strict policy fields
    trace_id: Optional[str] = None
    policy_version: str = "1.0.0"
    recommendation_type: str = "GENERAL"
    bounded_reason: str = ""
    max_allowed_impact: float = 0.0
    jurisdiction: str = "MV"  # Default to Maldives
    status: DecisionStatus = DecisionStatus.PENDING

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class AiOutput(BaseModel):
    """Full output containing multiple decisions."""
    trace_id: str
    decisions: List[AiDecision]
    metadata: Dict[str, Any]
