"""
MIG-AIGM Sovereign Root Constants.
Establishes the foundation of the SINGULARITY core.
"""

ROOT_IDENTITY = "MALDIVES INTERNATIONAL GROUP PVT LTD (UEI: 2024PV12395H)"
REGISTRATION_CODE = "C17892024"
TIN = "1166708"
MANAGING_DIRECTOR = "ABDULLA RASHEED (A096158)"

# Doctrine version
CORE_VERSION = "v1.2 [GENESIS-SEAL]"
